version: "3.5"
networks:
  voice:
    driver: bridge
    enable_ipv6: false    
    ipam:
      driver: default
      config:
        - subnet: 10.50.0.0/24
          gateway: 10.50.0.1
  control:
#    driver: default
    
volumes:
  data:

services:
  amqbus:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQBUS_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${AMQBUS_PASSWD:-guest}
      - RABBITMQ_DEFAULT_VHOST=${AMQBUS_VHOST:-/}
    networks:
      - control
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672
  fswitch:
    image: greicodex/freeswitch
    build:
      dockerfile: docker/freeswitch.Dockerfile
#    network_mode: host
    networks:
      voice:
        ipv4_address: 10.50.0.2
      control:
    volumes:
      - data:/data
      - ./config:/config
      - ./tmp:/tmp
    environment:
      - VOICE_IP=10.50.0.2
      - RABBITMQ_USER=${AMQBUS_USER:-guest}
      - RABBITMQ_PASSWORD=${AMQBUS_PASSWD:-guest}
      - RABBITMQ_SERVER=amqbus
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=${AMQBUS_VHOST:-/}
    ports:
      - "18021:8021"
      - "5060:5060/udp"
      - "5080:5080/udp"
      - "5061:5061"
      - "5081:5081"
      - "7443:7443"
      - "5070:5070"
      - "16384-16394:16384-16394/udp"
      

# $ Softphone running on the Browser
  softphone:
    image: nginx:stable-alpine
    container_name: sip-phone
    ports:
      - 8443:443
    volumes:
      - ./ctxSip:/usr/share/nginx/html
      - ./cert.pem:/root/ssl/cert.pem
      - ./key.pem:/root/ssl/key.pem
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf 
    restart: always