version: "3.5"
networks:
  voice:
    driver: bridge
    enable_ipv6: false
#    ipam:
#      driver: default
#      config:
#        - subnet: "192.168.238.0/24"
#        - subnet: "2001:3984:3989::/64"
    
    
volumes:
  data:

services:
  fswitch:
    image: greicodex/freeswitch
    build:
      dockerfile: docker/freeswitch.Dockerfile
    networks:
      voice:
#        ipv4_address: 192.168.238.5
#        gateway: 172.18.238.1
    volumes:
      - data:/data
      - ./config:/config
      - ./tmp:/tmp
    ports:
      - "18021:8021"
      - "5060:5060"
      - "5080:5080"
      - "5061:5061"
      - "5081:5081"
      - "7443:7443"
      - "5070:5070"
      - "16384-16394:16384-16394/udp"
      
